version: '3.8'

services:
  web:
    build: ./django-app
    image: simple-django-app
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django-app:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///db.sqlite3

volumes:
  db_data:
