version: '3.8'

services:
  db:
    build: ./db
    image: postgres:13
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  web:
    build: ./django-app
    image: simple-django-app
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django-app:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db_data:
