version: '3.8'

services:
  django:
    build: ./django-app
    container_name: django-app
    ports:
      - "8000:8000"
    volumes:
      - ./django-app:/app
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=your_db_name
      - DB_USER=your_db_user
      - DB_PASSWORD=your_db_password

  db:
    image: postgres:13
    container_name: db
    environment:
      POSTGRES_DB: your_db_name
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # Si tienes un contenedor para Nginx o Gunicorn, puedes añadirlo aquí
  # nginx:
  #   build: ./nginx
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - django
